
kind: template
load: node_baseline.yaml
data:
  argo_repo: https://github.com/paulpbrandon/argo-tests.git
  deployment_file_dev: kustomizehelloworld/base/deployment.yaml
  deployment_file_prod: kustomizehelloworld/overlays/hw-prod/kustomization.yaml
  docker_registry: paulsregistry80.azurecr.io
  docker_container: node-test