apiVersion: v1
kind: Service
metadata:
  name: droneserver
  labels:
    name: droneserver
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: nimblepaultestdrone
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: droneserver
