apiVersion: v1
kind: PersistentVolume
metadata:
  name: drone-disk-volume
  labels:
    type: local
spec:
  storageClassName: managed-csi
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
