apiVersion: apps/v1
kind: Deployment
metadata:
  name: dronerunner
  labels:
    app.kubernetes.io/name: dronerunner
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dronerunner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dronerunner
    spec:
      containers:
      - name: runner
        image: drone/drone-runner-kube:latest
        ports:
        - containerPort: 3000
        env:
        - name: DRONE_RPC_HOST
          value: "nimblepaultestdrone.uksouth.cloudapp.azure.com"
        - name: DRONE_RPC_PROTO
          value: "https"
        - name: DRONE_RPC_SECRET
          valueFrom:
            secretKeyRef:
              name: drone-secrets
              key: rpcsecret
        - name: DRONE_NAMESPACE_DEFAULT
          value: "drone"
